package com.oracle.web.bean;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.fname
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String fname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.name
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.chuban
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String chuban;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.zhuangtai
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.jieshuren
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private String jieshuren;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.f_id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    private Integer fId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.fname
     *
     * @return the value of book.fname
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.fname
     *
     * @param fname the value for book.fname
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.name
     *
     * @return the value of book.name
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.name
     *
     * @param name the value for book.name
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.chuban
     *
     * @return the value of book.chuban
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getChuban() {
        return chuban;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.chuban
     *
     * @param chuban the value for book.chuban
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setChuban(String chuban) {
        this.chuban = chuban == null ? null : chuban.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.zhuangtai
     *
     * @return the value of book.zhuangtai
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.zhuangtai
     *
     * @param zhuangtai the value for book.zhuangtai
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai == null ? null : zhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.jieshuren
     *
     * @return the value of book.jieshuren
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public String getJieshuren() {
        return jieshuren;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.jieshuren
     *
     * @param jieshuren the value for book.jieshuren
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setJieshuren(String jieshuren) {
        this.jieshuren = jieshuren == null ? null : jieshuren.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.f_id
     *
     * @return the value of book.f_id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public Integer getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.f_id
     *
     * @param fId the value for book.f_id
     *
     * @mbg.generated Tue May 07 17:10:48 CST 2019
     */
    public void setfId(Integer fId) {
        this.fId = fId;
    }

	public Book(Integer id, String fname, String name, String price, String chuban, String zhuangtai, String jieshuren,
			Integer fId) {
		super();
		this.id = id;
		this.fname = fname;
		this.name = name;
		this.price = price;
		this.chuban = chuban;
		this.zhuangtai = zhuangtai;
		this.jieshuren = jieshuren;
		this.fId = fId;
	}

	public Book() {
		super();
		// TODO Auto-generated constructor stub
	}
    
    
}